### ISSUE TITLE
Doesn't work on osx

### ISSUE THREAD

**Issue by ok2ju** [malte-wessel/react-custom-scrollbars#102]
Doesn't work on osx. It uses native scroll. Even examples doesn't work.
![screen shot 2016-11-22 at 14 50 20](https://cloud.githubusercontent.com/assets/3332170/20522864/696b78e2-b0c3-11e6-9810-b1072df50cd9.png)

OS: macOS Sierra 10.12.1
Browser: Chrome 54, also in Safari 10.0.1

**Comment by danbrianwhite** [comment]
This is fixed by open pull request #97.

**Comment by dodekeract** [comment]
And I was thinking "woah this looks great" assuming that this would look like this for all os/browser combinations. 😞

**Comment by ok2ju** [comment]
@malte-wessel Sorry, this issue again related to OSX overlay scrollbars. I read your explanation about this and understood your point. Thank you for your attention. We can close this issue.
