### ISSUE TITLE
Module build failed: Error: Couldn't find preset "stage-1"

### ISSUE THREAD

**Issue by joeLloyd** [malte-wessel/react-custom-scrollbars#115]
I have my project set to stage-0 so it doesn't find it by default.
But this dependency is not installed when i use the package.
I don't see why it needs this dependency since it should be compiled and not need babel build tools.

**Comment by dodekeract** [comment]
@joeLloyd are you absolutely sure that this is caused by `react-custom-scrollbars`? I'm using it in a project with `stage-0` and `es2015` presets. Haven't had that issue yet.

**Comment by joeLloyd** [comment]
It appears to be coming from `react-custom-scrollbars`. I think something is failing in the npm install.
could be my npm+node versions
npm: 2.15.8
node: v4.4.7

**Comment by joeLloyd** [comment]
to fix this i had to install stage-1 also
this, to me doesn't make sense but it worked so that cool.

**Comment by incleaf** [comment]
I faced the same problem and for some reason, my webpack reads `.babelrc` inside of `react-custom-scrollbars`. So it's not caused by `react-custom-scrollbars` either.

**Comment by herzaso** [comment]
I had the same issue with `es2015` preset. Installing it in my package instead of `env` fixed the issue although this doesn't seem right
