### ISSUE TITLE
scrollTo event

### ISSUE THREAD

**Issue by vnguyen94** [malte-wessel/react-custom-scrollbars#119]
First off, great library. I need to scroll to a certain element in the container, what would be the best way to do that?

**Comment by malte-wessel** [comment]
* reference scrollbars component and the element you want to scroll to
* grab the top position of the element inside the container
* call `scrollbars.scrollTop(topPositionOfElement)`

**Comment by ke1vin4real** [comment]
`element.scrollTop` is always 0
