### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by elverskog** [malte-wessel/react-custom-scrollbars#12]
When I cd into examples/simple and "npm install" then "npm start" I get this in the cli...

ERROR in ./index.js
Module build failed: Error: Couldn't find preset "react" relative to directory "/home/ddd/react/react-custom-scrollbars"

If I cd back into the root of your project and then "npm install" there I get it to work (react etc wasn't in node_modules). I had some travails along the way but maybe its worth a note in the README. I assume that most people are installing this into a woking react environment so maybe that is why this was missed.

**Comment by malte-wessel** [comment]
Thx for reporting! I'll update the README.
