### ISSUE TITLE
"Server-side React render was discarded." when used non-apple mouse with Mac

### ISSUE THREAD

**Issue by seleckis** [malte-wessel/react-custom-scrollbars#122]
When I use non-apple mouse with my Mac, macOS enables fixed width scrollbars. `react-custom-scrollbars` detects them as expected and shows custom scrollbars. But this causes an error in console log: 
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) :touch;margin-right:-15px;margin-bottom:
 (server) :touch;margin-right:0;margin-bottom:0;" 
printWarning @ warning.js:36
warning @ warning.js:60
_mountImageIntoNode @ ReactMount.js:507
mountComponentIntoNode @ ReactMount.js:112
perform @ Transaction.js:140
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ client.js:35
(anonymous) @ main-51cc2ce….js:2005
__webpack_require__ @ bootstrap 51cc2ce…:555
fn @ bootstrap 51cc2ce…:86
(anonymous) @ bootstrap 51cc2ce…:578
__webpack_require__ @ bootstrap 51cc2ce…:555
(anonymous) @ bootstrap 51cc2ce…:578
(anonymous) @ bootstrap 51cc2ce…:578
client.js:46 Server-side React render was discarded. Make sure that your initial render does not contain any client-side code.
```
No problems when using trackpad and Magic mouse. No problems on windows with the same mouse.

![screen shot 2017-02-10 at 11 18 26](https://cloud.githubusercontent.com/assets/988504/22821447/c58fd11e-ef83-11e6-927d-2acadd3b4cee.png)

**Comment by malte-wessel** [comment]
did you add the universal property?
`<Scrollbars universal/>`

**Comment by seleckis** [comment]
Oh, sorry, missed this flag. `universal` made the magic!

**Comment by orszaczky** [comment]
I had another warning in Chrome:
`warning.js:33 Warning: Prop `style` did not match. Server: "position:absolute;top:0;left:0;right:0;bottom:0;overflow:scroll;-webkit-overflow-scrolling:touch;margin-right:0;margin-bottom:0" Client: "position:absolute;top:0;left:0;right:0;bottom:0;overflow:scroll;-webkit-overflow-scrolling:touch;margin-right:-17px;margin-bottom:-17px"`.

adding `universal` also solved it
