### ISSUE TITLE
Not working mac os x

### ISSUE THREAD

**Issue by AveVlad** [malte-wessel/react-custom-scrollbars#128]
![image](https://cloud.githubusercontent.com/assets/2889662/23089942/30c0d9f4-f5a3-11e6-811d-0f5d89613d4b.png)

![image](https://cloud.githubusercontent.com/assets/2889662/23089951/510dc4a6-f5a3-11e6-8ade-d29ebf20269d.png)

![image](https://cloud.githubusercontent.com/assets/2889662/23089953/5c6d305c-f5a3-11e6-93d6-37d95c0c6cfb.png)

```
Google Chrome Version 56.0.2924.87 (64-bit)
Safari Version 10.0.3 (11602.4.8.0.1)
```

**Comment by AveVlad** [comment]
![image](https://cloud.githubusercontent.com/assets/2889662/23142400/c97ed292-f7cc-11e6-83f0-a84aa97e0183.png)


![image](https://cloud.githubusercontent.com/assets/2889662/23142451/113d1c6a-f7cd-11e6-86de-d3c94fb1963d.png)

**Comment by malte-wessel** [comment]
This is intended. See #53 #21 #73
