### ISSUE TITLE
Smooth Scroll For Methods

### ISSUE THREAD

**Issue by tarkanlar** [malte-wessel/react-custom-scrollbars#13]
Is it possible scroll smoothly with the methods like "scrollToBottom()" ?

**Comment by malte-wessel** [comment]
I added an example, which shows how to animate with scrollTop().
[Demo](http://malte-wessel.github.io/react-custom-scrollbars/) & [Code](https://github.com/malte-wessel/react-custom-scrollbars/tree/master/examples/simple/components/SpringScrollbars)

Hope that helps!

**Comment by tarkanlar** [comment]
Thanks @malte-wessel.Works perfectly =)

**Comment by tuannda94** [comment]
Thanks @malte-wessel. Please make the same to scrollLeft().

**Comment by darklightblue** [comment]
Or if you don't want to install/use `rebound` you can do:

```
const scrollbar = useRef(null); // or this.scrollbar = React.createRef(); if you're not using hooks

scrollbar.current.scrollbar.view.scroll({
    top: 0,
    behavior: 'smooth',
 });
```
If you are using refs

**Comment by muhaimincs** [comment]
> .scroll({
>     top: 0,
>     behavior: 'smooth',
>  });

not working

**Comment by darklightblue** [comment]
> not working

I updated the comment, make sure that `scrollbar` is a ref, It worked for me. 

That's the code I used in a website that I'm developing. I'm using react scrollbars 4.2.1. If it still doesn't work then you might try their solutions above.

**Comment by muhaimincs** [comment]
is this native scroll?

**Comment by darklightblue** [comment]
This is somehow what I did:

```
import React, { useRef } from 'react';
import { Scrollbars } from 'react-custom-scrollbars';
  
export default function ComponentName(props) {
  const scrollbar = useRef(null);
  const scrollToTop = () => {
    if (!scrollbar || !scrollbar.current) {
      return;
    }

    scrollbar.current.scrollbar.view.scroll({
      top: 0,
      behavior: 'smooth',
    });
  };

  return (<Scrollbars
    onScrollFrame={handleScroll}
    ref={scrollbar}
    // other refs
    >
         // content
        <button onClick={scrollToTop}>Scroll to top</button>
    </Scrollbars>
  );
}
```

Now I didn't bother looking whether they are doing something with the "scroll" function or they just call the native scroll function directly or not, but that's how I did it.

**Comment by Adidi** [comment]
loose the extra scrollbar and it will work:
```
scrollbar.current.view.scroll({
                top: 0,
                behavior: 'smooth',
              })
```

**Comment by shrue348** [comment]
simple css-selector hack
`
:global {
    [style*=overflow] {
      scroll-behavior: smooth;
    }
}
`
