### ISSUE TITLE
d.ts not updated

### ISSUE THREAD

**Issue by eyal1990** [malte-wessel/react-custom-scrollbars#133]
The d.ts of the project is not updated.
The main problem is the inclusion of this line:
> import React = __React;

When using @types/react there is no global variable named __React and so this file breaks the build.
The solution is kind of easy - omit the d.ts file from the project. 
This way, whoever wants to use the d.ts will use @types/react-custom-scrollbars which don't use the global __React variable.

(In a way, inserting the d.ts was a breaking change for everyone who used @types/react).

Let me know what you think.

**Comment by aalenliang** [comment]
+1 the .d.ts file in project breaks usage.

**Comment by malte-wessel** [comment]
I'm not quite familiar with TypeScript, would be cool if someone made a PR to fix this!

**Comment by aalenliang** [comment]
1. remove the index.d.ts file,
2. and delete
  "typings": "index.d.ts",
section in package.json.

**Comment by aalenliang** [comment]
https://github.com/malte-wessel/react-custom-scrollbars/pull/135

**Comment by malte-wessel** [comment]
Fixed by #135
