### ISSUE TITLE
Warning after React update

### ISSUE THREAD

**Issue by StipJey** [malte-wessel/react-custom-scrollbars#147]
> Warning: getInitialState was defined on Scrollbars, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
Pls, check and fix it :)

**Comment by alexpaxton** [comment]
I am also having this issue

**Comment by miguelBinpar** [comment]
Same here

**Comment by malte-wessel** [comment]
fixed in 4.1.1
