### ISSUE TITLE
height/width values for scrollbars get overridden

### ISSUE THREAD

**Issue by lifeifei** [malte-wessel/react-custom-scrollbars#15]
We would like to change the horizontal scrollbar height as it looks smaller than the normal scrollbar in IE. At this moment, the height is hard coded in your code.  Is there any way that we can customise it?

**Comment by malte-wessel** [comment]
Yes, that's easy!

```javascript
<Scrollbars
  renderScrollbarHorizontal={(style, ...props) =>
    <div style={{...style, height: 10 }} {...props}/>
  }/>
```

Check out the [customization](https://github.com/malte-wessel/react-custom-scrollbars#customization) section in the README

**Comment by lifeifei** [comment]
Hi,

I still get '6px' height for the horizontal scrollbar after using the above code.  Other customised styles work fine except the height as I guess it was overridden by your code when rendering.   Can you please confirm it?  Thanks!

Lifei

**Comment by malte-wessel** [comment]
Oh, you're right, I'll fix it soon!

**Comment by lifeifei** [comment]
I've forked your repo and fixing now. Would you like me to create a pull request after the fix?

**Comment by malte-wessel** [comment]
There are some other things, related to that specific code, that I'd also like to fix. So you don't need to make a PR. I'll fix this issue on the weekend.

**Comment by malte-wessel** [comment]
This should work now! Thx for reporting!
