### ISSUE TITLE
windowScrollTo(0, 0) doesn't work on App

### ISSUE THREAD

**Issue by Pau1fitz** [malte-wessel/react-custom-scrollbars#159]
When a user changes routes I have been scrolling the window to the top of the screen using `windowScrollTo(0, 0);`

Since introducing this library this no longer works due to the positioning set by the scrollbars library.

Is there a way to get around this?

My code looks like the following.

```
const handlePageChange = () => {
	window.scrollTo(0, 0);
};

// render the application
ReactDOM.render(
  <Provider store={store}>
    <Router onUpdate={handlePageChange} history={browserHistory}>
       <Redirect from="/" to="/music" />
           {routes}
      </Router>
   </Provider>,
  document.getElementById('root')
);
```

**Comment by yss14** [comment]
If I understand you right, your whole content is wrapped with this library now?
If so, you can reference the `Scrollbars` container and then call `scrollTop(0)`.
