### ISSUE TITLE
add id to containing div

### ISSUE THREAD

**Issue by racheldelman** [malte-wessel/react-custom-scrollbars#164]
Hi,
I'm trying to set the scroll position manually and I'm having trouble selecting the div that has `overflow: scroll`. Is there a way to add an id to that div? 

example code:
```
document.getElementById("scrollContainer").scrollTop += 100
```
where scrollContainer would be the div that scrolls

Thanks!

**Comment by sidonaldson** [comment]
Just add a ref to your instance and then use the API provided

```
<Scrollbars ref={(el) => (this.scrollbars = el)} />
```

```
componentDidUpdate() {
	this.scrollbars.scrollTop(0);
}
```
