### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by alexanderby** [malte-wessel/react-custom-scrollbars#18]
Is there a way to use this plug-in with Bower package manager and AMD?

**Comment by malte-wessel** [comment]
I'm not planning to support Bower. Here is why: http://gofore.com/ohjelmistokehitys/stop-using-bower/
Please use [npm](http://npmjs.com) and a bundler like [Webpack](http://webpack.github.io) [Browserify](http://browserify.org/)

**Comment by malte-wessel** [comment]
Now supported. See #23
