### ISSUE TITLE
Change color of scrollbar?

### ISSUE THREAD

**Issue by webchaz** [malte-wessel/react-custom-scrollbars#180]
I'd like to change the color of the scrollbar with an inline style.  I see the examples for `renderTrackHorizontal` but can't seem to figure out how to change the actual handle itself.  Would like to adjust the opacity of it.

Thanks!

**Comment by tacnoman** [comment]
The same for me.

**Comment by webchaz** [comment]
Just to comment on this, this was the solution (for vertical handle), I was using the wrong render:

```
<Scrollbars renderThumbVertical={({ style, ...props }) =>
   <div {...props} style={{ ...style, backgroundColor: '#000, width: '4px', opacity: '0.5'}}/>
}>
```

**Comment by pavle-lekic-htec** [comment]
For me this does not have any effect on the handle itself.
