### ISSUE TITLE
Scroll shadow example

### ISSUE THREAD

**Issue by t1mmen** [malte-wessel/react-custom-scrollbars#19]
First off, thanks for an awesome plugin! It is by far the best implementation of custom scrollbars I've seen, well done!

My question: Is there a way to listen to the scrollable area dimensions changing, typically because of a browser window resize? 

Use case: I'm implementing scroll shadow, like https://twitter.com/hakimel/status/685057803396988928, and currently I'm calculating viewport dimensions `onScroll`. When I resize the browser window, the shadow placement doesn't update, since `onScroll` doesn't fire.

My fallback plan is to listen to `window.onresize`, but figured I'd see if this is planned/already supported.

Thanks again!

**Comment by malte-wessel** [comment]
I made a new example for that: [Code](https://github.com/malte-wessel/react-custom-scrollbars/tree/master/examples/simple/components/ShadowScrollbars) & [Demo](http://malte-wessel.github.io/react-custom-scrollbars/).

Hope it helps!

**Comment by t1mmen** [comment]
Thank you, I figured that'd be the way :) Feel free to close this issue!
