### ISSUE TITLE
Update to support React 16

### ISSUE THREAD

**Issue by renanpvaz** [malte-wessel/react-custom-scrollbars#190]
These are the breaking changes: https://github.com/facebook/react/releases/tag/v16.0.0. 
I tried running your tests with react 16.0.0 and made some fixes, still [this test](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/test/Scrollbars/universal.js#L46) won't pass. If you have any idea of what it could be I can fix it and send a PR.

**Comment by cyl19910101** [comment]
Maybe it's because of React 16's new SSR strategy? The style won't be updated in some situations. https://github.com/facebook/react/issues/10591

**Comment by renanpvaz** [comment]
@cyl19910101 any ideas of what could fix it?

**Comment by malte-wessel** [comment]
Should be fixed with v4.2.0
