### ISSUE TITLE
scrollTop does not work programmatically

### ISSUE THREAD

**Issue by junkiemonkey** [malte-wessel/react-custom-scrollbars#193]
Hello!
Why this:
>class Scroll extends Component { 
 &nbsp; &nbsp;componentDidMount() {
      &nbsp;&nbsp;&nbsp;&nbsp;this.scroll.scrollTop(150);
   &nbsp;&nbsp; }
  &nbsp;&nbsp;render {
    &nbsp;&nbsp;&nbsp;&nbsp;return <Scrollbars ref={s => { this.scroll = s; }}> .... </Scrollbars>
 &nbsp;&nbsp; }
} 

not working? Work only user on click event...

**Comment by a-m-dev** [comment]
+++++++++1
