### ISSUE TITLE
Set height and width via CSS instead of inline styles

### ISSUE THREAD

**Issue by snaumov** [malte-wessel/react-custom-scrollbars#207]
Hi,

first of all, thanks for great package! 

I've been trying to adopt it and faced with the following issue - as I can see the only way to specify the height and width of scrollable content at the moment is by passing it explicitly as inline style:

`<Scrollbars style={{ width: 500, height: 300 }}>
        <p>Some great content...</p>
      </Scrollbars>`

However, in v.2 of this package it was possible also to set the dimensions via CSS: 

https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/v2-documentation.md

> If you use renderScrollbarHorizontal, make sure that you define a height value with css or inline styles

So, I'm curious if it's possible to achieve the same behavior now - add the CSS class to Scrollbars with defined height/width?

**Comment by isoceles** [comment]
I was able to use css for setting the height. 

`<Scrollbars className="scrollHeight">`

`.scrollHeight {
    height: calc(100vh - 7.4rem) !important;
  }
`

Make sure you use !important to give priority to your styling over the default styles.

**Comment by snaumov** [comment]
Well, that will work, but we're kind of prohibited to use !important on our project :) But thanks for you suggestion anyway.

**Comment by AlonBe** [comment]
In case it helps, if you use "autoHeight" mode you can use "autoHeightMin" and "autoHeightMax" props to set the minimum/maximum height

**Comment by snaumov** [comment]
@AlonBe not really, that's not related to my question I'm afraid :)

As I see it's not possible at the moment to set height via CSS, so closing.
