### ISSUE TITLE
Native scrollbars for mobile devices not working.

### ISSUE THREAD

**Issue by nghiepdev** [malte-wessel/react-custom-scrollbars#214]
Hi guys,

Version  4.2.1  currently, native scrollbars for mobile devices not working.

**Comment by samosad** [comment]
Hi! Same problem. Did you manage to fix it somehow?

**Comment by nghiepdev** [comment]
@samosad I'm moved to [smooth-scrollbar-react](https://github.com/nghiepit/smooth-scrollbar-react)
