### ISSUE TITLE
Rendering inside hidden dom node

### ISSUE THREAD

**Issue by matthisk** [malte-wessel/react-custom-scrollbars#22]
When I render a react component with Scrollbars inside a dom node that is hidden through 'display: none' property, I get a couple of error messages complaining about "Component has no static height". The reason would be that the height of a dom node that is not rendered in the dom can not be determined. However when I set a static height on Scrollbars and on the dom node returned by ``renderView`` I still get the error message, is this expected behavior?

**Comment by malte-wessel** [comment]
I removed the warnings. It's hard to determine whether the scrollbars are just hidden or a width/height property has not been set.
