### ISSUE TITLE
Support for AMD/RequireJS

### ISSUE THREAD

**Issue by alexanderby** [malte-wessel/react-custom-scrollbars#23]
Is there a way to use this package with AMD/RequireJS? I tried to use Browserify, but could not load resulting bundle using RequireJS and it seems like it included all the dependencies like React and ReactDOM.

**Comment by frankietaylor** [comment]
It will be better if its available as a separate js file to be included in the browser, without node/browserify/webpack.

**Comment by malte-wessel** [comment]
I'm working on a solution. I'll probably make a a bundled file available via npmcdn.com. That would also work for bower. (related: #18)

**Comment by frankietaylor** [comment]
Thanks. Will it be possible to have the bundle without react?

**Comment by malte-wessel** [comment]
yes, the bundle will only inlcude the `raf` and `dom-css` dependencies, since they are not available through bower (I guess)

**Comment by malte-wessel** [comment]
AMD, RequireJS and bower are now supported. You can grab the bundles from npmcdn:
[Development build](https://npmcdn.com/react-custom-scrollbars@3.0.1/dist/react-custom-scrollbars.js), [Production build](https://npmcdn.com/react-custom-scrollbars@3.0.1/dist/react-custom-scrollbars.min.js). If you want to use bower you can install it via:

```javascript
bower install react-custom-scrollbars=https://npmcdn.com/react-custom-scrollbars@3.0.1/dist/react-custom-scrollbars.js
```
You should also check the [docs on installation](https://github.com/malte-wessel/react-custom-scrollbars#installation)
I made an [example on CodePen](http://codepen.io/drbreak/pen/KVEMyd) how to use the build.

**Comment by alexanderby** [comment]
Thank you very much. Works great.
