### ISSUE TITLE
Miscalculation of Thumb Position

### ISSUE THREAD

**Issue by jfurrow** [malte-wessel/react-custom-scrollbars#24]
I noticed there's a miscalculation of the thumbnail's position. I have a massive list where the thumbnail gets super tiny, and when scrolling toward the bottom of the list, the thumbnail is moved well beyond the bottom of the viewport. See the attached gif, in which I scroll to the bottom of the list after the thumb moves out of view:
![](http://johnfurrow.com/share/scrolling-bug.gif)

I suspect it's due to using a percentage in the `transform` property, and the calculated height of the thumb isn't the same as the rendered height of the thumb.

As an aside, it would be nice to be able to specify a `min-height` for the thumb.

**Comment by malte-wessel** [comment]
Thanks for reporting! This seems to be a rounding bug with percentages in webkit browsers. Firefox doesn't show this behaviour. I fixed this by using absolute pixel values. I'll soon release a v3.0.0-beta with these changes. `min-height` for thumbs will also be supported.

**Comment by jfurrow** [comment]
Awesome, thank you!

**Comment by malte-wessel** [comment]
This is fixed in v3.0.0. Also check out the [API](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/API.md) on `thumbMinSize` and the [upgrade guide](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/upgrade-guide-v2-v3.md)

**Comment by jfurrow** [comment]
Thank you, this looks awesome! I'll implement it in my project later today. Great work!
