### ISSUE TITLE
Library is not working

### ISSUE THREAD

**Issue by rus-yurchenko** [malte-wessel/react-custom-scrollbars#244]
Seem like library is not working. On the demo page from repo it looks like default scroll bar. Screenshoot attached.
<img width="140" alt="screenshot 2018-03-23 21 41 19" src="https://user-images.githubusercontent.com/10502916/37850296-46d609f6-2ee3-11e8-8b69-8f363773c184.png">

**Comment by ChristopherChudzicki** [comment]
This is the behavior I see also in up-to-date chrome and safari. Fidding with `renderThumbVertical` and `renderTrackVertical` seems to have no effect.

**Comment by devniel** [comment]
I've same error, it seems that is something related to Chrome.
