### ISSUE TITLE
Should Scrollbar include wheel listeners?

### ISSUE THREAD

**Issue by quisido** [malte-wessel/react-custom-scrollbars#252]
Re: schrodinger/fixed-data-table-2/issues/316

I have an issue where when react-custom-scrollbars is floating over an element with a wheel listener, react-custom-scrollbars will not scroll.

The details are outlined further in the other issue, but I'll summarize here:

Scrollbar floats above DataTable.
Scrollbar has a scroll event listener to move its scrollbar.
DataTable has a wheel event listener to move its scrollbar.
DataTable's wheel event listener calls `event.preventDefault()`.
The mouse is positioned over the Scrollbar element.
The mouse wheel is moved.
The Scrollbar element does not respond, as it has no wheel event listener.
The event propagates to background elements.
The DataTable's wheel event listener fires and prevents the scroll event from firing.
DataTable scrolls in response to the mouse wheel event.
Scrollbar never receives a scroll event.
Scrollbar never scrolls.

Contrary to expected behavior, the background element is now scrolling instead of the custom scrollbar, simply due to the fact that the background element has a wheel event listener.

Should the custom scrollbar have a wheel event listener to capture scroll attempts by the user? Or would you say this is an issue with the background element?

**Comment by quisido** [comment]
@malte-wessel Hope this repo isn't abandoned.

**Comment by xobotyi** [comment]
@CharlesStover may be add the wheel listener to view element of custom scroll on your own and make `event.stopPropagation()` ?
