### ISSUE TITLE
Scrollbar not showing on component Render for in React-Router Component

### ISSUE THREAD

**Issue by ponty96** [malte-wessel/react-custom-scrollbars#26]
I have routes with react-router set as this
```
const routes = (
<Route component={MainComponent} path="/">
     <Route component={Component1} path="/no-scrollbar"/>
     <Route component={Component2} path="/show-scrollbar"/>
</Route>
)
```

If I visit `myapp.com/show-scrollbar` the scrollbar is not shown unless I press the `arrow down|up key of my keyboard` but its shown automatically if i get to this `route` through react-router `Link` component.
I don't know why this is so and I'm doing anything that affects the state of this component. The component just renders and all its component within except the scrollbar component. Btw I'm also `server rendering` my whole app with `webpack `and have not encountered this problem with the other components that I'm using.

**Comment by malte-wessel** [comment]
Could you provide some code or a repo that reproduces the bug? Then I'll have a look at it.

**Comment by ponty96** [comment]
That will be tricky cause I'm using it on an app @ work but I'll see if I can replicate the same bug with a similar code base

**Comment by malte-wessel** [comment]
Maybe related to #38

**Comment by malte-wessel** [comment]
Any updates on this?

**Comment by malte-wessel** [comment]
I'll close this for now, please reopen, If you got updates on this!
