### ISSUE TITLE
Feature Request: Option to Position Track left or top

### ISSUE THREAD

**Issue by serle** [malte-wessel/react-custom-scrollbars#262]
Would it be possible to add a property to position the vertical track on the left hand side of the content panel. Likewise to position the horizontal track on the top of the content panel.

**Comment by zhuqiqi19941122** [comment]
hey , have you found a solution ? Facing the same question right now

**Comment by malte-wessel** [comment]
That is possible, check out this pen: https://codepen.io/drbreak/pen/yGEGWe
