### ISSUE TITLE
Feat req: Duration and easing params on scroll methods

### ISSUE THREAD

**Issue by corysimmons** [malte-wessel/react-custom-scrollbars#267]
`containerRef.scrollTop(targetRef.offsetTop, 2000, 'ease-out')` would be so cash. Happy to see this functionality introduces in stages: duration first with linear ease, then fancier easing stuff later.

**Comment by malte-wessel** [comment]
You can already implement your own animation behaviour. Check out https://github.com/malte-wessel/react-custom-scrollbars/blob/master/examples/simple/components/SpringScrollbars/SpringScrollbars.js
