### ISSUE TITLE
integrate resize sensor to update scrollbar

### ISSUE THREAD

**Issue by Justin-ZS** [malte-wessel/react-custom-scrollbars#268]
In my case, the component size may be changed without updating.
But scrollbar component only recalculates correct position during updating.
So the scrollbar doesn't show when needed, or the opposite.

**Comment by Justin-ZS** [comment]
Implement by myself. This repo is unmaintained

**Comment by sahilchopra** [comment]
Hi @Justin-ZS 
Can you please share your logic of resize
