### ISSUE TITLE
How can this be used for horizontally?

### ISSUE THREAD

**Issue by linonetwo** [malte-wessel/react-custom-scrollbars#27]
I'm not sure whether I should use renderThumbHorizontal, or it can only do vertical work ...
thanks.

**Comment by malte-wessel** [comment]
What are you trying to do? Did you check out the [documentation on customization](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/customization.md)?

**Comment by malte-wessel** [comment]
If you need horizontal Scrollbars make sure, that your content is wider than the `Scrollbars` element: 

```javascript
<Scrollbars style={{ width: 400, height: 300 }}>
  <div style={{ width: 800 }}>Your content</div>
</Scrollbars>
```

**Comment by tegozen** [comment]
wtf? fixed width children? and if there are children inside who depend on content?
