### ISSUE TITLE
Applying classes to different sub-components

### ISSUE THREAD

**Issue by lveillard** [malte-wessel/react-custom-scrollbars#276]
Hello there,

It would be awsome to be able to change the style of the scrollbar (for example show it only when the content is hovered and hide it if not)

Having classNames on each sub-component would ease this custommization :)

**Comment by spone379** [comment]
Waiting for solving this issue!)

**Comment by spone379** [comment]
@saityro You need to look at this section
https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/customization.md

**Comment by lveillard** [comment]
Yep! I tried but i was kind of new to react so it was a bit difficult for me. I think it wouldn't be a bad idea to have those classNames by default, that would definitively ease the customization.

I will try to do it again eventually (after two weeks i'm more into react haha)  and post the solution here if I get it, in case it helps somebodyin the future 🚀

**Comment by spone379** [comment]
@saityro I can explain to you)
For example you need to customize your vertical track. You only put this string like a props.
`renderTrackVertical={props => <div {...props} className="track-vertical"/>}`

So now you have the div that will be your VerticalTrack with `className="track-vertical"`.
And you can add some style in your css file. For example:
```
.track-vertical {
  position: absolute;
  width: 6px;
  right: 2px;
  bottom: 2px;
  top: 2px;
  border-radius: 3px;
  background: #BFBFBF; }
```

And for your Thumb you need to add prop 
`renderThumbVertical={props => <div {...props} className="thumb-vertical"/>}`
and write css like:

```
.thumb-vertical {
  position: relative;
  display: block;
  width: 100%;
  cursor: pointer;
  border-radius: inherit;
  border: 1px solid #BFBFBF;
  background-color: #E6EBF1;
  height: 10px;
  transform: translateY(0px); }
```

Hope this help!:wink:

**Comment by paddotk** [comment]
@spone379 I tried this but it doesn't work for me. The className is not actually applied. Also doing `renderThumbVertical={props => <div {...props} style={{stuff}} />}` doesn't work. What am I missing?

**Comment by spone379** [comment]
@paddotk Create a sandbox (https://codesandbox.io) with your example and I'll look at it.

**Comment by lveillard** [comment]
Super thanks! I'm eager to test it. Hope I will get some time this week so i can confirm it works in my case (and do a little codesanbox in case it can help somebody!)

**Comment by paddotk** [comment]
@spone379 Thank you, I figured it out via a comment on a different issue, with the inline styling it works now. I think I was missing a spread operator on my custom style object, or perhaps i didn't merge it with the passed `style` prop.

**Comment by lveillard** [comment]
Worked like a charm! thank you @spone379
