### ISSUE TITLE
Allow custom event handlers on thumb

### ISSUE THREAD

**Issue by jellyfish-tom** [malte-wessel/react-custom-scrollbars#277]
Right now it s not possible to add mouseDown event to scroll thumb as it will get overwritten by library code. Would be nice if user could pass own method in onMouseDown prop and it will be handled by lib code. I can implement it, lets just agree on how it should be handled. 

In lib code there are those lines:

    thumbHorizontal.addEventListener('mousedown', this.handleHorizontalThumbMouseDown);
    thumbVertical.addEventListener('mousedown', this.handleVerticalThumbMouseDown);

Doing simply:

    thumbHorizontal.addEventListener('mousedown', () => {
        this.handleHorizontalThumbMouseDown()
        this.props.onMouseDown() // function passed by user
    })

would solve the issue and allow user plugging into those events. 
Not perfect, I know, but usable for sure.

**Comment by kkowalczuk** [comment]
I've been struggling with that issue recently and I came up with the solution satisfying my needs (also not perfect - the `onMouseDown` simulation is delayed until the user unhovers the scrollbar container, but does not require messing with the library internals and helps to achieve the behaviour similar to `onMouseDown`):

```js
class YourComponent extends React.Component {

  ...

  leftButtonPressedWhenHovering= false
  eventSet = false

  handleMouseEnterOnScrollbar = (e) => {
    this.leftButtonPressedWhenHovering = e.buttons === 1
  }

  handleMouseUpInsideDocument = (e) => {
    document.removeEventListener("mouseup", this.handleMouseUpInsideDocument)
    this.eventSet = false
  }

  handleMouseLeaveOffScrollbar = (e) => {
    if (!this.leftButtonPressedWhenHovering && e.buttons === 1 && !this.eventSet) {
      /* your mouse down logic here */
      document.addEventListener("mouseup", this.handleMouseUpInsideDocument)
      this.eventSet = true
    }
  }

  handleMouseUpInsideScrollbar = (e) => {
    this.leftButtonPressedWhenHovering = false
  }

  renderVerticalThumb = () => {
    return (
      <div
        onMouseEnter={this.handleMouseEnterOnScrollbar}
        onMouseLeave={this.handleMouseLeaveOffScrollbar}
        onMouseUp={this.handleMouseUpInsideScrollbar}
      />
    )
  }

  componentWillUnmount() {
    if (this.eventSet) {
      document.removeEventListener("mouseup", this.handleMouseUpInsideDocument)
      this.eventSet = false
    }
  }

  render() {
    ...
    return (
      <Scrollbars {...yourProps} renderThumbVertical={this.renderVerticalThumb}>
        ...
      </Scrollbars>
    )
  }
}
```

Ideally it would be great to receive custom `onMouseDown` support on custom horizontal/vertical scrollbar containers from the library, but I'm leaving the above piece of code here so it may save somebody's time.

**Comment by malte-wessel** [comment]
Thanks @kkowalczuk, that is the preferred solution!

**Comment by plysik** [comment]
This should be mentioned in documentation. I've been struggling with same issue for few days...
