### ISSUE TITLE
the libary dot't work  when i set css_moudles

### ISSUE THREAD

**Issue by saga7878** [malte-wessel/react-custom-scrollbars#289]
thanks for your libary ,In most cases it works fine.  in react v^16.5.2 , i set css_moudles, if i don't set  ::-webkit-scrollbar  Series of property, it's dose'nt work; beccause scrollbars allways display none in css

**Comment by jiameng123** [comment]
￼￼

**Comment by saga7878** [comment]
![image](https://user-images.githubusercontent.com/21330858/46912185-ff50c300-cfa0-11e8-9692-7ff232a2cade.png)
![image](https://user-images.githubusercontent.com/21330858/46912192-2a3b1700-cfa1-11e8-8d6a-dfecba3a6837.png)
