### ISSUE TITLE
Proposal: Show Scrollbar on hover

### ISSUE THREAD

**Issue by Escapado** [malte-wessel/react-custom-scrollbars#29]
Hey,

I would like to propose that there could be an option to show the scrollbar when you hover over the container.
That would be really amazing for an upcoming version! Also thanks a lot for the cool component!!

Cheers

**Comment by envex** [comment]
This can be done via css.

Let's say I have a component setup like this:

```
<Scrollbars
	className="custom-scrollbars">

	{this.props.children}

</Scrollbars>
```

You can setup the cssto be something along the lines of:

```
.custom-scrollbars .track{
	opacity: 0
	transition: opacity 200ms ease
}

.custom-scrollbars:hover .track{
	opacity: 1
}
```

**Comment by malte-wessel** [comment]
Thx @envex .Closing this for now...

**Comment by envex** [comment]
No problem!

**Comment by lookapanda** [comment]
This .track class is never set.

**Comment by shaikshavalis** [comment]
.track class is never set, how to display the track on hover ?

**Comment by towfiqi** [comment]
`.track` class is never set. Its not possible to style the trackbar.

**Comment by vladpavlovski** [comment]
> This .track class is never set.

.track class is for prop renderTrackVertical

 ```
renderTrackVertical = ({ style, ...props }) => {
    return (
      <div
        className='track'
        {...props}
        />
    )
  }

<Scrollbars
    className="custom-scrollbars"
    renderTrackVertical={this.renderTrackVertical}
>
    {this.props.children}

</Scrollbars>
```

**Comment by Rahulzz** [comment]
This should do the trick

.custom-scrollbars > div:last-child {
    opacity: 0;
    transition: opacity 200ms ease;
}

.custom-scrollbars:hover > div:last-child {
    opacity: 1;
}
