### ISSUE TITLE
How to scroll only one direction when in mobile

### ISSUE THREAD

**Issue by kingller** [malte-wessel/react-custom-scrollbars#297]
Hi, 
   My scrollbar appears both horizontally and vertically, and when I use gestures to scroll in mobile, the scrollbar scrolls horizontally and vertically at the same time. Can I customize it to scroll only to one direction depending on the direction of the slide?

**Comment by malte-wessel** [comment]
The component should work like normal scrollbars do. Did you try to ensure that you don't have an overflow on the respective axis?

**Comment by kingller** [comment]
My problem is,  scrollbars appear both vertically and horizontally in a div. When I use gestures to slide, for example, I slip a long distance in the vertical direction, but there is a 5px offset in the horizontal direction. At this time, I expect to scroll in the vertical direction only, and not in the horizontal direction. How can I do it?

**Comment by malte-wessel** [comment]
Do you have an online example? Codepen or something?

**Comment by kingller** [comment]
Here is my online example: [https://codesandbox.io/embed/4ro0wkj83w](https://codesandbox.io/embed/4ro0wkj83w). You can visit [https://4ro0wkj83w.codesandbox.io/](https://4ro0wkj83w.codesandbox.io/) on mobile

**Comment by kingller** [comment]
Maybe it can't be done in this way. This is the problem of native scrollbar. I switched to use simulated scrollbar when in mobile.
