### ISSUE TITLE
Initial Scroll Position

### ISSUE THREAD

**Issue by camdagr8** [malte-wessel/react-custom-scrollbars#313]
I'm using this component to create a scrollable area inside another component. 

I'm saving the `scrollTop` value to redux `onScrollStop` and then applying it in the update function of the parent component. 

Using the API, I have to target the scrollbar ref, but it's not always available on mount or update, so I have to encapsulate my update with a `setTimeout`. 

When I do this, there's a slight flicker showing the default scrollTop. 

I've looked at the other issues here about this topic and none of the solutions work for me. 

So I have a feature request: 
**initialPostion prop** 

I tried implementing this myself, but I can't seem to figure out where to put a routine for setting the initial scrollTop.. there's just so much going on in the `render()` method.

**Comment by camdagr8** [comment]
So I found a work around for my issue. It's not perfect but close enough I guess: 

```javascript
<Scrollbars
    ref={elm => {
        this.scrollbar = elm;
        elm.scrollTop(500);
    }}>
    content
</Scrollbars>
```

So basically you have to do it when the ref is set.

**Comment by Eviwang** [comment]
TypeError: scrollBar.scrollTop is not a function. why?
