### ISSUE TITLE
onUpdate

### ISSUE THREAD

**Issue by kamicane** [malte-wessel/react-custom-scrollbars#33]
I'm in need of an onUpdate prop to properly implement infinite/finite scrolling, as onScroll/onScrollFrame only happen when you scroll, not whenever update() is called (e.g. window is resized, or on componentDidUpdate)

In the meantime, I'm using a rather hackish solution, inside my componentDidMount:

```js
componentDidMount () {
  const scrollbars = this.refs.scrollbars
  const update = scrollbars.update
  scrollbars.update = (cb) => {
    update((values) => {
      if (cb) cb(values)
      this.handleUpdate(values)
    })
  }
  const values = scrollbars.getValues()
  this.handleUpdate(values)
}
```

if onUpdate fired only when values are actually changed that would be a plus, as for instance, the window could be resized and have zero effect on the Scrollbars component.

**Comment by malte-wessel** [comment]
Yes, I thought about that case. I'll see what I can do at the weekend.

**Comment by malte-wessel** [comment]
Okay, `onUpdate` is in. Update to `3.1.0`. Check out the [API docs](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/API.md)
