### ISSUE TITLE
Scrollbar overlaps content.

### ISSUE THREAD

**Issue by ErikParso** [malte-wessel/react-custom-scrollbars#342]
Hello, is there a way to set scrollbar to not overlap content ? Or, determine if scroll bar will show so i can set margin right to content (except if scrollbar is not needed) ?

![image](https://user-images.githubusercontent.com/35962203/72267461-63d55480-3620-11ea-9cff-209113c15e45.png)

My scrollbar is defined following..
![image](https://user-images.githubusercontent.com/35962203/72267585-9c752e00-3620-11ea-9b75-7acb64276b2b.png)
![image](https://user-images.githubusercontent.com/35962203/72267614-a6972c80-3620-11ea-9b25-718cc9c31cb9.png)

**Comment by arpitprod** [comment]
I added renderView props in Scrollbars

```
<Scrollbars
    renderView={props => <div {...props} className="scrollbar-view" />}
>
```
and in css,

```
.scrollbar-view {
    padding-right: 20px;
}
```
and it's working for me

**Comment by ErikParso** [comment]
> I added renderView props in Scrollbars
> 
> ```
> <Scrollbars
>     renderView={props => <div {...props} className="scrollbar-view" />}
> >
> ```
> 
> and in css,
> 
> ```
> .scrollbar-view {
>     padding-right: 20px;
> }
> ```
> 
> and it's working for me

**Comment by ErikParso** [comment]
@arpitprod Thanks for tip but when scrollbar isnot needed there is an unecessary padding right.

**Comment by arpitprod** [comment]
you can do like this
If scroll bar needed. you can define a variable 

> const isScrollBar = true;

and then check isScrollBar for add class

```
<Scrollbars
    renderView={props => <div {...props} className={isScrollBar ? "scrollbar-view" : ""} />}
>
```

If you don't need scrollbar then change isScrollBar value to false and no class will add

**Comment by ErikParso** [comment]
@arpitprod If scrollbar is needed is determined dynamicaly by content (i have dynamic number of items in container). Scrollbar is automatically rendered if content is larger than container. Your approach is good but i have to determine, whether the scroll bar is visible or not :)

**Comment by arpitprod** [comment]
If You know, what is the height of container and what is the height of single content. So, you know how much items can show in the container without scrollbar.
It's showing 6 items in container without scrollbar now.
So, check if items.length greater than 6 then scrollbar style will apply

```
<Scrollbars
    renderView={props => <div {...props} className={items.length > 6 ? "scrollbar-view" : ""} />}
>
```

**Comment by ErikParso** [comment]
Yes this would be an simple solution but items in container are not same height and have a lots of variants. 
![image](https://user-images.githubusercontent.com/35962203/76880695-5a62a580-6878-11ea-8fbc-aee9ffe2da88.png)
I want to create universal container (wrapper) with this crollbar. Ill close this issue, i only wanted to know if there is an simple solution for this. I see comparing dom elemets heights to determine if scrollbar is needed is only solution for now.
