### ISSUE TITLE
Causing scroll behavior on mouse drag

### ISSUE THREAD

**Issue by bunkat** [malte-wessel/react-custom-scrollbars#35]
I have a list that is sortable via drag and drop within a scrollable view using react-custom-scrollbars.  Is there any way to force the scroll region to scroll if the user is holding down the mouse button and drags to the bottom of the region?

**Comment by malte-wessel** [comment]
Yes, I think there should be a way to do this. Look at the [ShadowScrollbars example](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/examples/simple/components/ShadowScrollbars/ShadowScrollbars.js). There are two divs at the top and the bottom. You could register a `mousedown` handler and on the `<Scrollbars>` component (or the wrapper) and a `mousemove` on the top/bottom divs. If you drag an element (`mousedown`) and the mouse enters one of the divs (`mousemove`) you could do a step-wise scrolling with `scrollbars.scrollTop(x)`.

Let me know if this works.

**Comment by malte-wessel** [comment]
by the way: I noticed that in chrome this works out of the box.

**Comment by malte-wessel** [comment]
After thinking again about it, you could also do this without the additional divs.
Register an `mousemove` handler on the `<Scrollbars>` component and while dragging check the distance between pointer and upper/lower edge. If it's near of one of the edges, scroll up/down.

**Comment by bunkat** [comment]
That worked perfectly.  Thanks!

**Comment by raghav1086** [comment]
@malte-wessel @bunkat Do you have any example for this. I am also facing same issue, would be great help if you could provide any example of it.
