### ISSUE TITLE
Customization does not work inside a reactstrap modal

### ISSUE THREAD

**Issue by I2obiN** [malte-wessel/react-custom-scrollbars#356]
To be clear normal props and the default ScrollBars element works fine. However following:
https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/customization.md

The text seems to be hidden. Let me illustrate,
![image](https://user-images.githubusercontent.com/7683830/85299990-ebf83980-b49d-11ea-9a80-3b65ed0ec1c8.png)

I have followed the Customization documentation as far as I can see
![image](https://user-images.githubusercontent.com/7683830/85300100-0df1bc00-b49e-11ea-89a7-1792bf00f456.png)

Hmm, where has my text gone? Let's investigate.
![image](https://user-images.githubusercontent.com/7683830/85300273-41344b00-b49e-11ea-9e14-740954994314.png)

Well it's still there but it is position absolute? All the thumb elements are there and the classname is correct. What's happened?
![image](https://user-images.githubusercontent.com/7683830/85300433-70e35300-b49e-11ea-9f0a-54747078c047.png)

This isn't critical for me but I don't see what I'm getting wrong. The background color is getting set, do I need to pass through anything else in the styles prop?

**Comment by sakhnyuk** [comment]
Hi. 
I see that, you doesnt set height of Scrollbars. Try something like that:

```jsx
<Scrollbars autoHeight autoHeightMin={500}> {your content} </Scrollbars>
```

**Comment by I2obiN** [comment]
Working now, thanks.
