### ISSUE TITLE
macOS System Preferences break package

### ISSUE THREAD

**Issue by kyleshevlin** [malte-wessel/react-custom-scrollbars#368]
This issue is intended to provide information to the author/maintainer and hopefully help anyone else who may be having similar issues. It seems there are a number of issues that are macOS specific and I found at least part of the problem.

I was attempting to debug why no custom scrollbars were showing for me at all. Not in Chrome, Firefox, or Safari. It turns out it is a System Preferences issue.

Unless you have General > Show scrollbars set to `Always` when you load a page with `react-custom-scrollbars`, you will not be shown the custom scrollbars, and if you do manage to get them to render, there's a good chance that the thumb will be the full height of the scrollable area or some similar issue.

![Screen Shot 2020-11-04 at 4 00 48 PM](https://user-images.githubusercontent.com/4333144/98182942-e1be6100-1ebb-11eb-9700-7ff2d5f4c6d1.jpg)

Thus far, I've been adding some breakpoints in the library code trying to find the source of the bug, but I can only make a hunch. It seems that `getVerticalThumbHeight` does not get called if your system preferences are set to any other option. It might not be the only method that isn't called. I believe what might be happening is that the ref to the actual scroll bar is lost because it's added and removed by the browser. This is an educated guess at this time, though.

I hope this is helpful.

**Comment by sheixt** [comment]
Thanks for the insight @kyleshevlin been banging my head with this for sometime. Did you manage to find a workaround?

**Comment by kyleshevlin** [comment]
@sheixt Sorry, I don't have a solution. I was able to leverage this roadblock into changing the requirements for the task, so I didn't have an incentive to continue trying to find a fix. Truth is, I never wanted to do custom scrollbars in the first place.

I know that doesn't help you and I'm sorry for that. Best of luck.

**Comment by sheixt** [comment]
@kyleshevlin thanks for getting back to me :) Yeah I wasn't keen on replacing the scrollbars myself. We've opted for some device detection to revert to using webkit's styling. It was a quick win as the main motivation for using the package was more for styling browsers without such APIs.

**Comment by kyleshevlin** [comment]
I'm closing this because, honestly, I'm tired of it being in my issues tab. I'm fairly certain this will never get worked on by the library contributors and I have no reason to work on this as I'm no longer a part of the project where I discovered this issue. I'm sorry to anyone who comes across this and wish you luck.
