### ISSUE TITLE
Incorrect thumb height on the initial render

### ISSUE THREAD

**Issue by jeremejevs** [malte-wessel/react-custom-scrollbars#38]
I'm using `Scrollbars` as a wrapper of the whole page. It works fine, but the [vertical] thumb is `0px` high on the initial render. Once I scroll using a wheel / some other means, or resize the window, then the thumb's height is calculated correctly. I'm getting this only in Chrome, not Firefox.

I've set some breakpoints in the code, and it appears that `update`, and consequently `getThumbVerticalHeight`, is called only once, before the DOM is painted (the page is completely blank when the breakpoint is triggered). Apparently, having `raf` is not enough, since it's still somehow executed before the browser is done painting.

Not sure whose fault it is (React's or Chrome's, or maybe it's Firefox who's doing it wrong), but as pointed out in a [related SO question](http://stackoverflow.com/a/34999925/242684), the only way to do size-related DOM probes reliably is to have a 0ms timeout before invoking `raf`. And indeed, once I've added the following to the container:

```js
componentDidMount() {
  setTimeout(() => this.refs.scrollbars.forceUpdate(), 0);
}
```

... the issue went away.

Sorry for not providing a way to repro, this is as much time as I can commit to this, unfortunately.

**Comment by malte-wessel** [comment]
This sounds like you're doing some asnyc stuff inside your wrapped content on the initial rendering.
If your wrapped content isn't finally rendered when the `Scrollbars` component did mount, you'll probably get that problem. It would be great to have an example on codepen or jsfiddle that reproduces the bug.

**Comment by malte-wessel** [comment]
Could you check if it works, when the first `update` (triggered by `Scrollbars.componentDidMount`) is called without `raf` ?

**Comment by jeremejevs** [comment]
I've eliminated all the external factors while I was investigating - all children and decorators (e.g. `react-css-modules` in my case) - and even something as simple as this:

```js
render() {
  return (
    <Scrollbars>
      <div style={{ height: 4096 }} />
    </Scrollbars>
  )
}
```

... still wouldn't work without a timeout (or some other delayed re-render trigger).

And what do you mean by "without `raf`"? Do you want me to try modifying this component's code?

**Comment by malte-wessel** [comment]
Ok, that's strange. 

So, my idea was to avoid the `raf` on the initial rendering. I modified the built `Scrollbars` file here: https://gist.github.com/malte-wessel/86eb8cd6253523d484707ff280722395#file-scrollbars-modified-js-L521-L566

You could replace the source file (`node_modules/react-custom-scrollbars/lib/Scrollbars/index.js`) with this one and see if it works. (Yes, a little hacky, but that should do the job)

**Comment by jeremejevs** [comment]
I don't believe `raf` is at fault here. It probably doesn't affect anything at all, since it's called **before** the next repaint. But regardless, I've tried the patch, no effect. Are you unable to reproduce this?

**Comment by malte-wessel** [comment]
Sorry, can't reproduce the bug. Could you provide at least a PR with a failing test?

**Comment by jeremejevs** [comment]
I'll try finding time for this some time soon, just not a top priority, since the workaround works fine for me. What browser and OS are you using?

**Comment by malte-wessel** [comment]
Alright, I'm using OSX and Chrome

**Comment by malte-wessel** [comment]
Any updates on this?

**Comment by jeremejevs** [comment]
Sorry, not yet, simply don't have the energy. I suppose this can be closed, until further notice. Your call.
