### ISSUE TITLE
Can you remove peerDependencies?

### ISSUE THREAD

**Issue by wslp12** [malte-wessel/react-custom-scrollbars#383]
I am using this library.
Version:
"custom-custom-contract bars": "4.2.1",

And other developers are using my library.

My library react version is 15.3.2

And the other user's development environment is React version 17.
And when they use my library, the following problems occur.

default-cra@0.1.0 ...
├-┬ luna-rocket@1.1.0 (...)
│ ├-- UNMET PEER DEPENDENCY react@15.3.2
│ └-┬ react-append-to-body@2.0.1
│ └-- react@15.7.0
└-- react@17.0.1

npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-custom-scrollbars@4.2.1

I think we need to delete peerdependencies. Are you willing to delete it?

Please consider including the change of peerDependencies at npm7

**Comment by RobPethick** [comment]
We now support react v17 in react-scrollbars-2 https://github.com/RobPethick/react-custom-scrollbars-2
