### ISSUE TITLE
Styling scrollbars

### ISSUE THREAD

**Issue by asaadmahmoodspin** [malte-wessel/react-custom-scrollbars#39]
I'm trying to use these scrollbars in an app that has multiple themes, and without having a class on the scrollbars on the container it's hard for me to style the scrollbars. The current style which is `    background-color: rgba(0, 0, 0, 0.2);` doesn't go well with dark backgrounds.

**Comment by david-owens-akqa** [comment]
You can see how to add a className to the scrollbars here

https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/customization.md

**Comment by malte-wessel** [comment]
thx @david-owens-akqa

**Comment by golakjena** [comment]
not working in firefox mac
