### ISSUE TITLE
autoHide not working?

### ISSUE THREAD

**Issue by sashamjolnir** [malte-wessel/react-custom-scrollbars#40]
I dont want to scrollbar hiding, by default autoHide is false, but scrollbar is still hiding. Where am I wrong?

**Comment by malte-wessel** [comment]
Yes, autoHide should only be activated if you have the property set like:
```javascript
<Scrollbars autoHide/>
```

Could you provide some code?

**Comment by sashamjolnir** [comment]
oh, it was because Mac OS setting `Show scrollbars: When scrolling`.
sorry for issue. I come to another library, that shows scrollbars on Mac OS.
