### ISSUE TITLE
Custom thumb height

### ISSUE THREAD

**Issue by anatoliis** [malte-wessel/react-custom-scrollbars#42]
Hi! Is there a way to set a custom thumb height?

**Comment by malte-wessel** [comment]
Yes, there's a property for that:
```javascript
<Scrollbars thumbSize={50}/>
```
[Have a look at the API docs](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/API.md)

**Comment by anatoliis** [comment]
Sorry, my mistake :)

**Comment by malte-wessel** [comment]
never mind ;)

**Comment by pyros2097** [comment]
Well this wasn't there on the initial readme page and I tried thumbMinSize and it didn't work. Finally found this. Yes!
