### ISSUE TITLE
Spring Scroll to a Specific Paragraph (Div)

### ISSUE THREAD

**Issue by jmstiles34** [malte-wessel/react-custom-scrollbars#44]
Hello...I'm working with your Spring Scroller (which is awesome). I have 10 paragraphs in the scrollable component and each paragraph is within its own div with a ref. I'm trying to figure out if there is an easy way to calculate the scrollTop for a specific paragraph so I can bounce down to it on render. I can hardcode an integer value for each paragraph using [scrollbars.scrollTop(75)], but I was hoping to make it dynamic using the refs. Any suggestions on how this could be accomplished? Thanks!

**Comment by brandonmp** [comment]
```
<p id={'para1')>
lorem ipsum
</p>

```
```
handleScroll = (paragraphID) => {
  const top = document.getElementById(paragraphID).offsetTop
  this.refs.scrollbars.scrollTop(top)
}

```
i had some trouble getting the `SpringScrollbars` to work as written (it was scrolling to wrong position). i had to simplify the `rebound` code to just this: 

```
 scrollTop(top) {
    this.spring.setEndValue(top)
  }

```
