### ISSUE TITLE
Invert Scroll Bars

### ISSUE THREAD

**Issue by idealeric** [malte-wessel/react-custom-scrollbars#45]
I have a project where the primary direction a user would want to scroll is left/right as opposed to up/down scroll. I'd like to be able to invert the mouseWheel directions (as in up and down on the mouse wheel scrolls left and right).

I have forked and written a small patch that seems to work great for me and would like to contribute it back but want to make sure its a feature this project would like to support.

**Comment by malte-wessel** [comment]
See #46
