### ISSUE TITLE
autoHeight[Max|Min]

### ISSUE THREAD

**Issue by vieks** [malte-wessel/react-custom-scrollbars#48]
Could you please allow to set autHeightMax and autHeightMin with other units than default px ?

Anyway thanks for this nice component !

**Comment by malte-wessel** [comment]
Yes, thats a good idea! I'll put it on the Roadmap!

**Comment by vieks** [comment]
Thanks :+1:

**Comment by jar3k** [comment]
Yes! Would be great to have a posibility to set `autoHeightMax` on 100%.

**Comment by malte-wessel** [comment]
Ok, this is published in `4.0.0-beta.2`
