### ISSUE TITLE
The error in IE8

### ISSUE THREAD

**Issue by seraphimrose** [malte-wessel/react-custom-scrollbars#49]
Hello,

There will be the Error "Invalid argument" in IE8, in fact, I can't determine whose fault it is. (please forgive my laziness)

> const thumbHorizontalX = scrollLeft / (scrollWidth - clientWidth) * (trackHorizontalWidth - thumbHorizontalWidth);
> const thumbHorizontalStyle = {
>     width: thumbHorizontalWidth,
>     transform: `translateX(${thumbHorizontalX}px)`
> };

When the component is initializing, the value of `scrollWidth` and `clientWidth` will be the same, so that the `thumbHorizontalX` will be the NaN !

Then in `dom-css`, the action is `dom.style.transform = translateX(NaNpx)`, which the error "Invalid argument" will be throwed in IE8, and the application stops.(will be not in Chrome)

So the problem is "the same value of the scrollWidth and clientWidth", is there my fault?

**Comment by malte-wessel** [comment]
I think that `NaN` is not the problem, but trying to assign `dom.style.transform`, since this is not supported in IE8. However, I'm not planning to support IE8. But if you could do a PR that fixes the issue, I'll merge it.

**Comment by dyf2015** [comment]
we need support ie8 thank you

**Comment by fenghuizhang** [comment]
need support ie8 for my company ,hope you can fix it ,thank you very much!--- from china
