### ISSUE TITLE
[4.0.0-beta.2] autoHeight causes checksum mismatch in SSR

### ISSUE THREAD

**Issue by simonkberg** [malte-wessel/react-custom-scrollbars#52]
> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
> (client) bottom:0;min-height:15px;max-height:215p
> (server) bottom:0;min-height:0;max-height:200px;"

Server:
```css
position: relative;
overflow: hidden;
-webkit-overflow-scrolling: touch;
margin-right: 0;
margin-bottom: 0;
min-height: 0;
max-height: 200px;
```
Client:
```css
position: relative; 
overflow: scroll; 
margin-right: -15px; 
margin-bottom: -15px; 
min-height: 15px; 
max-height: 215px;
```

*Reformatted for readability*

**Comment by malte-wessel** [comment]
Oh yes, I didn't considered universal rendering, when implementing autoHeight. Should be easy to fix though. I'll put it on the road map

**Comment by malte-wessel** [comment]
Did you activate universal rendering mode?

```javascript
<Scrollbars universal/>
```

**Comment by simonkberg** [comment]
Yup. Ref: https://github.com/simonkberg/simon-kjellberg/blob/feature/scrollbars/src/chat/ChatMessageList.js#L144
