### ISSUE TITLE
Cursor in pointer mode over all across line of scrollbar

### ISSUE THREAD

**Issue by realcr** [malte-wessel/react-custom-scrollbars#54]
Hi,
When using the <Scrollbars /> component with default settings, I get cursor in pointer mode even in places where the scrollbar doesn't show. For example: My container only scrolls vertically, however I still have cursor in pointer mode everywhere near the bottom edge of the container.
I experience this behaviour both with firefox and chrome.

I tried to customize by supplying renderThumbVertical like this:

    renderThumb({style, ...props}) {
        const thumbStyle = {
            cursor: "default",

        };
        return ( 
            <div 
                style={{...style, ...thumbStyle}}
                {...props}
            />
        );
    }

But I still get the cursor in pointer mode all over the right edge of my container, even in places where the scrollbar is not present.

A possible fix for this problem would be a patch that deletes the "cursor: pointer" lines in defaultRenderElements.js. Besides fixing this bug, I think that this is the correct behaviour for scroll bars on containers. Note that default scroll bars do not trigger a pointer cursor.

**Comment by malte-wessel** [comment]
Thanks for reporting. I'll probably remove the default `cursor: pointer`.
