### ISSUE TITLE
Vertical scrollbar height did not update when the container height changed.

### ISSUE THREAD

**Issue by xancode** [malte-wessel/react-custom-scrollbars#55]
I am not sure whether this is an issue within react-custom-scrollbars.
I am posting this information here in case others find it useful as I have just spent a long time resolving the issue in my own code.

I used the react-custom-scrollbars component  within a redux container within a react-split-panel.
I found that the vertical scrollbar height did not update when I changed the split panel divider.
Luckily we had another instance of the custom scrollbars in the same app that worked perfectly.

After lots of debugging, I isolated the only significant difference to be the presence of the optional ownProps argument in the mapStateToProps function passed to the redux connect function. Without ownProps, the scrollbar did not update properly when the container height changed.

I suspect this has something to do with the following behaviour described in https://github.com/reactjs/react-redux/blob/master/docs/api.md.
"If ownProps is specified as a second argument, its value will be the props passed to your component, 
and mapStateToProps will be re-invoked whenever the component receives new props."

**Comment by malte-wessel** [comment]
Thanks for reporting! The Scrollbars component will only adjust its height, when it is updated (rerendered). Therefore you need to ensure, that whenever the panes size changes, the Scrollbars component is rerendered.

**Comment by malte-wessel** [comment]
Closing this for now

**Comment by dmikester1** [comment]
Is that what the onUpdate function is for?  Do we call that when the container height changes?
