### ISSUE TITLE
autoHeight question?

### ISSUE THREAD

**Issue by sundyxfan** [malte-wessel/react-custom-scrollbars#56]
Setting autoHeight does not work?

**Comment by malte-wessel** [comment]
Did you install `4.0.0-beta.2` ?

**Comment by sundyxfan** [comment]
"react-custom-scrollbars": "^3.1.0"

**Comment by malte-wessel** [comment]
install the latest beta version, which supports autoHeight:
`npm install react-custom-scrollbars@4.0.0-beta.2 --save`
