### ISSUE TITLE
autoHeight and autoHeightMax do not work together. No autoHeightMin={auto}

### ISSUE THREAD

**Issue by wzup** [malte-wessel/react-custom-scrollbars#59]
```
<Scrollbars autoHide={true} thumbMinSize={30} autoHeightMax={500} autoHeight={true}>
    {contents}
{/Scrollbars }
```

I want the scrollbar to emerge ONLY when `autoHeightMax={500}`. Before that height has to be auto. Right until 500px. With your props it is not possible.
You either have 

- `style={height: bla-bla-bla}` which is not an option. I don't need fixed height.

- `autoHeight={true} autoHeightMax={500}` which is not an option, because they confront each other. `autoHeight={true}` disables `autoHeightMax={500}` and `autoHeightMax={500}` gets just useless, it doesn't work with `autoHeight={true}`

- only `autoHeightMax={500}` doesn't make it. height of contents is 0.

`autoHeight="auto" autoHeightMax={500}` would do the trick but you don't have `autoHeight="auto"`

How to achieve desired behaviour?

**Comment by malte-wessel** [comment]
Auto height is only available in the latest version. Did you install v4.0.0-beta.2?
If not try `npm install react-custom-scrollbars@4.0.0-beta.2`
