### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by polkovnikov-ph** [malte-wessel/react-custom-scrollbars#6]
Scrolling a `div` with 100 `span`s loads one of the cores of Core i7 up to 100%.

**Comment by malte-wessel** [comment]
Hi, thanks for reporting! I'll plan to release a new version soon, which will set styles directly on the DOM nodes. This should improve performance significantly.

**Comment by malte-wessel** [comment]
This should be fixed with v2.0.0. Let me know if not.
