### ISSUE TITLE
Callback for autoHide

### ISSUE THREAD

**Issue by AStaroverov** [malte-wessel/react-custom-scrollbars#60]
Hi! In my case i want change container size after hidden scroll, i can do it with last version?
Else I think it will be good point.

**Comment by malte-wessel** [comment]
Not sure if I understand correctly, but If you want to do anything, when the users stops scrolling you could do it like:

```javascript
<Scrollbars onScrollStop={this.doSomething}/>
```

**Comment by AStaroverov** [comment]
U dont understand me) I want work with autoHide event. It would be great if props ``autoHide`` could take not only boolean, but and function, like this
```
<Scrollbars
  autoHide={state =>  console.log(state ? 'show' : 'hide')}
/>

**Comment by malte-wessel** [comment]
It's not possible to pass a function to the `autoHide` property, since this is just an option to activate the auto hide behaviour. However, you could get the desired behaviour with the following code:
```javascript
<Scrollbars
  autoHide
  onScrollStart={() => console.log('show')}
  onScrollStop={() => console.log('hide')}/>
```
