### ISSUE TITLE
Is it possible to get content to scroll for any scroll event?

### ISSUE THREAD

**Issue by mkellyclare** [malte-wessel/react-custom-scrollbars#61]
Say I have two Scrollbars sections side by side, is it possible to get them both to scroll at the same time when I scroll anywhere on the page, not just each one scrolling when it the cursor is over them.

Thanks.

**Comment by malte-wessel** [comment]
You can programmatically scroll when you have a reference to the component instance: `scrollbars. scrollTop(100)`
