### ISSUE TITLE
Start on bottom?

### ISSUE THREAD

**Issue by Ralvke** [malte-wessel/react-custom-scrollbars#62]
Good afternoon.
Is possible <ScrollArea /> will start (load) in bottom position?
_Yes, i am known when i can `scrollToBottom()` on loading, but in this case will animation. It spoils UI ((`_

Thanks.

**Comment by malte-wessel** [comment]
I'm not sure that this is possible. The library uses the native scrolling behaviour of the browser, and I'm not aware of any solution for this.

**Comment by artsx** [comment]
it would be good that this option is added!
For sites that use a tchat is handy

**Comment by enijar** [comment]
Add a ref to the `<Scrollbars ref="scrollbars"/>` component, then call `this.refs.scrollbars.scrollToBottom()`.

**Update**

In the new React versions you will have to call the scrollToBottom method on the scrollbars ref like this.

```js
class MyComponent extends React.Component {
  scrollbars = React.createRef();
  state = {
    mounted: false,
  }

  componentDidMount() {
    this.setState({mounted: true});
  }

  componentDidUpdate() {
    this.state.mounted && this.scrollbars.current.scrollToBottom();
  }

  render() {
    return <Scrollbars ref={this.scrollbars}/>;
  }
}
```

**Comment by jay-sharan** [comment]
@Enijar Worked for me. Thanks.

> Add a ref to the `<Scrollbars ref="scrollbars"/> `

> component, then call `this.refs.scrollbars.scrollToBottom()`.

**Comment by auaden** [comment]
i called this.refs.scrollbars.scrollToBottom() in componentDidMount(), doesn't work

**Comment by deepika1223** [comment]
is there is any alternative to "refs"?

**Comment by Agrafador** [comment]
@deepika1223 yes, you can do like this:

`constructor(props){
        super(props);
        this.msgsScrollbars = React.createRef();
    }`

`componentDidMount(){
        this.msgsScrollbars.current.scrollToBottom();
    }`

`<Scrollbars ref={this.msgsScrollbars}>`

**Comment by vijitail** [comment]
@Agrafador Your solution works but, the initial render starts from the top and jumps to the bottom when componentDidMount() is called. Any solution with componentWillMount() ?

**Comment by vedant-shah** [comment]
While using the useEffect i added the message variable as dependency and called the scrollToBottom as mentioned above. It does scroll to the bottom but i am unable to scroll up. What can i do ?

**Comment by MagicScripta** [comment]
> While using the useEffect i added the message variable as dependency and called the scrollToBottom as mentioned above. It does scroll to the bottom but i am unable to scroll up. What can i do ?

I think this is because it keeps scrolling to the bottom, try updating the use effect dependencies to something other than the message, maybe on message send.
