### ISSUE TITLE
hidden scrollbars still have pointer events

### ISSUE THREAD

**Issue by asterius1** [malte-wessel/react-custom-scrollbars#64]
If there is no need of scrollbar, it gets hidden, but it will still capture pointer evens.

For example in demos when you mouse over place where horizontal scrollbar would be, cursor is `pointer`. It will also block clicks events from passing to scrollable content below it.
Same thing if vertical scrollbar can be hidden.

It breaks user experience, when I use scrollbar in many small views.

**Comment by malte-wessel** [comment]
Thanks for reporting, I'll fix that in the next release. Related: #54

**Comment by malte-wessel** [comment]
fixed in v4.0.0
