### ISSUE TITLE
Correct work with React 15.2.0

### ISSUE THREAD

**Issue by ilfa** [malte-wessel/react-custom-scrollbars#67]
In new version React throw warnings if you try to add unknow props for in DOM Element. (https://github.com/facebook/react/releases/tag/v15.2.0)

If I pass `https://github.com/facebook/react/releases/tag/v15.2.0` property for example, I had this React warning:
```
warning.js:44 Warning: Unknown prop `hideTracksWhenNotNeeded` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Scrollbars)
```

**Comment by xiaoda** [comment]
I use this plugin in the sidebar of my project and then the warning appears on every page of my site! help!!! In my opinion it's easy to fix, just check the props passed to the component and then apply only those legal property to the DOM element. Hope author fix this and I will appreciate your work very much!

**Comment by malte-wessel** [comment]
Thx for reporting! Fixing this should be easy. I'm currently busy, but I think I'll release a new version next week with this issue fixed.

**Comment by damian4291** [comment]
Looks like if someone use ShadowScrollbars example 'onUpdate' prop also needs to be definited.

`index.js:8624 Warning: Unknown prop `onUpdate` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by fdaciuk** [comment]
Hey @malte-wessel, do you need any help to release the v4?

**Comment by fdaciuk** [comment]
Nice job @malte-wessel! Thanks a lot! :heart: :dancer: :sparkles:
