### ISSUE TITLE
100% scrollarea width cannot be overriden

### ISSUE THREAD

**Issue by polkovnikov-ph** [malte-wessel/react-custom-scrollbars#7]
I'm making a two column markup with each column being scrollable. It's impossible to set `width: 50%`.

**Comment by malte-wessel** [comment]
Could you provide some code?

**Comment by malte-wessel** [comment]
You could wrap the Scrollbars component in a div that has a width of 50%!?

**Comment by malte-wessel** [comment]
Please reopen if that doesn't help.
