### ISSUE TITLE
Support for system native scroll hiding

### ISSUE THREAD

**Issue by bulaj** [malte-wessel/react-custom-scrollbars#73]
On OS X (and propably other systems that allow it) there is an option to show scrolls only when scrolling, react-custom-scrollbars do not cover this case (just native scroll shows up, component doesnt seem to work at all).

Is there a workaround for that?
Is it even possible to make component work?

![screen shot 2016-07-26 at 11 28 30](https://cloud.githubusercontent.com/assets/5004407/17132926/34011cb8-5324-11e6-8034-65ceb6972bc8.png)

**Comment by malte-wessel** [comment]
This is not possible for various reasons. See #53 #21
