### ISSUE TITLE
Scrollbar Not Appearing when scroll using Trackpad

### ISSUE THREAD

**Issue by sivadass** [malte-wessel/react-custom-scrollbars#75]
I am having a strange issue, vertical scroll bar not appearing first instead horizontal scroll-bar is visible. But upon **mouse** scroll, horizontal scroll disappears as soon as vertical scroll-bar appears. Then the major issue is vertical scroll-bar is not even getting visible when scrolled using **trackpad**.

This is my minimal markup

```
<Scrollbars style={{ height: 345 }} className="product-list">
  <div className="product-row"></div>
  <div className="product-row"></div>
  <div className="product-row"></div>
  .
  .
  .
</Scrollbars>
```

**Comment by KatiRasanen** [comment]
I have the same problem that the scrollbars do not get visible when using trackpad. External trackpad you can at least disable and then the scrollbar works, but if the laptop has an integrated trackpad scrollbar won't work at all.

**Comment by sivadass** [comment]
This problem solved for me after setting height and width to the parent of the <Scrollbars/> component.

**Comment by KatiRasanen** [comment]
Ok, thanks! Although I think that's not possible in my case. :/
