### ISSUE TITLE
'event' parameter missing on handleHorizontalTrackMouseDown

### ISSUE THREAD

**Issue by norbiu** [malte-wessel/react-custom-scrollbars#76]
I noticed that clicking on the horizontal track in **Firefox** didn't cause the thumb to move, while the vertical scrollbar seems to be working correctly. Both scrollbars work fine in Chrome.

The problem is with a missing `event`parameter in [handleHorizontalTrackMouseDown()](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/src/Scrollbars/index.js#L314).

**Comment by malte-wessel** [comment]
Thx for reporting. I'll put it on the roadmap
