### ISSUE TITLE
scrollbar not update when scrollbar in flex boxes change

### ISSUE THREAD

**Issue by heeju** [malte-wessel/react-custom-scrollbars#77]
scrollbars are not update when flex box change
![animation 1](https://cloud.githubusercontent.com/assets/3131509/17292646/739ab71a-5826-11e6-8c77-d9798baca901.gif)

It only changes when window resize
can you fix it?

**Comment by malte-wessel** [comment]
If you change your layout, make sure you render the `<Scrollbars/>` component again. This will update the dimensions.

**Comment by heeju** [comment]
OK I see. thanks
