### ISSUE TITLE
Disable horizontal scrollbar

### ISSUE THREAD

**Issue by Amdingo** [malte-wessel/react-custom-scrollbars#8]
I'm sure this (is...) seems silly, but I'm nesting the scrollbars quite deep and can't seem to figure out how to disable horizontal scrolling.

**Comment by malte-wessel** [comment]
There's actually no explicit way to do this. You need to make sure that the view element's height is less or equal the scrollbars element's height.

**Comment by rknDA1337** [comment]
Whats an implicit way of dealing with it then? If possible, sorry.

I just started using this and my child elements are animated in and out with css3 which is the only time the horizontal scroll bars are shown (they disappear when the element has settled).

**Comment by optimatex** [comment]
@rknDA1337 u can render ur custom horisontal scroll box `renderTrackHorizontal={props => <div {...props} className="track-horizontal"/>}` and set ur own desireable styles

**Comment by wayofthefuture** [comment]
I don't understand how a scrolling library cannot disable X scrolling.

**Comment by MenaDev** [comment]
Buenas tardes, estoy tratando con un Iframe con react.js pero tengo un problema con las barras de desplazamiento, cuando quiero visualizar el contenido que tengo en el iframe se me muestra la barra del iframe y el de la pagina padre tambien, si alguien tiene una sugerencia como poder deshabilitar el scroll vertical, gracias.
