### ISSUE TITLE
scrollbarWidth should be computable on server side

### ISSUE THREAD

**Issue by benwiley4000** [malte-wessel/react-custom-scrollbars#85]
I'm using server side initial rendering and my checksum is invalidated when the client render check runs because the scrolling element's margins change in response to `scrollbarWidth`, which is currently only detectable in the client.

I haven't experimented with this much, but is it impossible to force a `scrollbarWidth` independent of client, rather than always accepting the browser default?

**Comment by malte-wessel** [comment]
Did you try the universal property? https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/usage.md#universal-rendering

**Comment by benwiley4000** [comment]
Not sure how I missed this in the documentation. Thank you! It's exactly what I needed. :smiley:

**Comment by benwiley4000** [comment]
Not that [here](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/API.md) the link to "Learn how to use universal rendering" is broken.
