### ISSUE TITLE
Force visible (even on mobile)

### ISSUE THREAD

**Issue by rivertam** [malte-wessel/react-custom-scrollbars#99]
Would it be possible to force the scrollbars to be visible always? My design is kind of dependent on the scrollbars, even on mobile, so I would like them to be visible even in the case of mobile devices.

Is this possible? I looked through the source and can't find where the logic to make them hidden for mobile is.

**Comment by rivertam** [comment]
After some research, it seems this might be completely impossible. Would love some confirmation that it's impossible.

**Comment by malte-wessel** [comment]
Yes, this is not possible. See #53 #21 #73

**Comment by rivertam** [comment]
=/ thanks anyways. Great library!
